name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  BuildJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1

      - name: Print current working directory
        run: echo Current working directory is ${{github.workspace}}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x
          
      - name: Update package version using run attempt
        uses: tuandinhnz/my-actions/SetNugetPackageVersion@main
        with:
          version: ${{github.run_number}}

      - name: Verify package version
        run: |
          echo The current directory is $(pwd)
          for i in $(find . -type f -iname "*.csproj"); do cat $i; done

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release -o bin/Release/

      - name: Upload NuGet package to GitHub
        uses: actions/upload-artifact@v4.3.4
        with:
          name: cybertek-core-artifact
          path: bin/Release/
          retention-days: 7
          
  PublishToNuget:
    runs-on: ubuntu-latest
    needs: BuildJob

    steps:
      - name: Download nuget package artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: cybertek-core-artifact
        
      - name: Publish to Github Package
        run: |
          dotnet nuget add source --username tuandinhnz --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/tuandinhnz/index.json"
          for pkg in $(find . -iname "*.nupkg"); do dotnet nuget push $pkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"; done
          
  
