name: Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  BuildJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Build begins ..."
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
